package cn.hospital.pojo;

import java.util.Date;

public class Doctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.section_id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private Integer sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.doctor_id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.doctor_name
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.doctor_password
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private String doctorPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.doctor_mobile
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private String doctorMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.create_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.modify_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.id
     *
     * @return the value of hospital_doctor.id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.id
     *
     * @param id the value for hospital_doctor.id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.section_id
     *
     * @return the value of hospital_doctor.section_id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.section_id
     *
     * @param sectionId the value for hospital_doctor.section_id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.doctor_id
     *
     * @return the value of hospital_doctor.doctor_id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.doctor_id
     *
     * @param doctorId the value for hospital_doctor.doctor_id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.doctor_name
     *
     * @return the value of hospital_doctor.doctor_name
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.doctor_name
     *
     * @param doctorName the value for hospital_doctor.doctor_name
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.doctor_password
     *
     * @return the value of hospital_doctor.doctor_password
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public String getDoctorPassword() {
        return doctorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.doctor_password
     *
     * @param doctorPassword the value for hospital_doctor.doctor_password
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setDoctorPassword(String doctorPassword) {
        this.doctorPassword = doctorPassword == null ? null : doctorPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.doctor_mobile
     *
     * @return the value of hospital_doctor.doctor_mobile
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public String getDoctorMobile() {
        return doctorMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.doctor_mobile
     *
     * @param doctorMobile the value for hospital_doctor.doctor_mobile
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setDoctorMobile(String doctorMobile) {
        this.doctorMobile = doctorMobile == null ? null : doctorMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.create_date
     *
     * @return the value of hospital_doctor.create_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.create_date
     *
     * @param createDate the value for hospital_doctor.create_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.modify_date
     *
     * @return the value of hospital_doctor.modify_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.modify_date
     *
     * @param modifyDate the value for hospital_doctor.modify_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}