package cn.hospital.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Drugs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_drugs.id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_drugs.drugs_id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private Integer drugsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_drugs.drugs_name
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private String drugsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_drugs.drugs_type
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private String drugsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_drugs.drugs_number
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private Integer drugsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_drugs.drugs_price
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private BigDecimal drugsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_drugs.create_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_drugs.modify_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_drugs.id
     *
     * @return the value of hospital_drugs.id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_drugs.id
     *
     * @param id the value for hospital_drugs.id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_drugs.drugs_id
     *
     * @return the value of hospital_drugs.drugs_id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public Integer getDrugsId() {
        return drugsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_drugs.drugs_id
     *
     * @param drugsId the value for hospital_drugs.drugs_id
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setDrugsId(Integer drugsId) {
        this.drugsId = drugsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_drugs.drugs_name
     *
     * @return the value of hospital_drugs.drugs_name
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public String getDrugsName() {
        return drugsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_drugs.drugs_name
     *
     * @param drugsName the value for hospital_drugs.drugs_name
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setDrugsName(String drugsName) {
        this.drugsName = drugsName == null ? null : drugsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_drugs.drugs_type
     *
     * @return the value of hospital_drugs.drugs_type
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public String getDrugsType() {
        return drugsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_drugs.drugs_type
     *
     * @param drugsType the value for hospital_drugs.drugs_type
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setDrugsType(String drugsType) {
        this.drugsType = drugsType == null ? null : drugsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_drugs.drugs_number
     *
     * @return the value of hospital_drugs.drugs_number
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public Integer getDrugsNumber() {
        return drugsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_drugs.drugs_number
     *
     * @param drugsNumber the value for hospital_drugs.drugs_number
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setDrugsNumber(Integer drugsNumber) {
        this.drugsNumber = drugsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_drugs.drugs_price
     *
     * @return the value of hospital_drugs.drugs_price
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public BigDecimal getDrugsPrice() {
        return drugsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_drugs.drugs_price
     *
     * @param drugsPrice the value for hospital_drugs.drugs_price
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setDrugsPrice(BigDecimal drugsPrice) {
        this.drugsPrice = drugsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_drugs.create_date
     *
     * @return the value of hospital_drugs.create_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_drugs.create_date
     *
     * @param createDate the value for hospital_drugs.create_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_drugs.modify_date
     *
     * @return the value of hospital_drugs.modify_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_drugs.modify_date
     *
     * @param modifyDate the value for hospital_drugs.modify_date
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}