package cn.hospital.pojo;

public class MedicalWithBLOBs extends Medical {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_medical.basic_info
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private String basicInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_medical.medical_record
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    private String medicalRecord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_medical.basic_info
     *
     * @return the value of hospital_medical.basic_info
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public String getBasicInfo() {
        return basicInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_medical.basic_info
     *
     * @param basicInfo the value for hospital_medical.basic_info
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setBasicInfo(String basicInfo) {
        this.basicInfo = basicInfo == null ? null : basicInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_medical.medical_record
     *
     * @return the value of hospital_medical.medical_record
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public String getMedicalRecord() {
        return medicalRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_medical.medical_record
     *
     * @param medicalRecord the value for hospital_medical.medical_record
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    public void setMedicalRecord(String medicalRecord) {
        this.medicalRecord = medicalRecord == null ? null : medicalRecord.trim();
    }
}