package cn.hospital.dao;

import cn.hospital.pojo.Doctor;
import cn.hospital.pojo.User;
import org.apache.ibatis.annotations.Param;

public interface DoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_doctor
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insert(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_doctor
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insertSelective(Doctor record);

    /**
     * 验证医生用户名和密码
     * @param doctorId 医生编码
     * @param doctorPassword 医生密码
     * @return
     */
    Doctor selectDoctorByParam(@Param("doctorId") int doctorId,
                               @Param("doctorPassword") String doctorPassword);
}