package cn.hospital.dao;

import cn.hospital.pojo.Drugs;

public interface DrugsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_drugs
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insert(Drugs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_drugs
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insertSelective(Drugs record);
}