package cn.hospital.dao;

import cn.hospital.pojo.MedicalWithBLOBs;

public interface MedicalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_medical
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insert(MedicalWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_medical
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insertSelective(MedicalWithBLOBs record);
}