package cn.hospital.dao;

import cn.hospital.pojo.News;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_news
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_news
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insertSelective(News record);
}