package cn.hospital.dao;

import cn.hospital.pojo.Patient;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_patient
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_patient
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insertSelective(Patient record);

    /**
     * 根据日期查询挂号单
     * @param date 日期
     * @return 返回挂号列表
     */
    List<Patient> selectPatientListByDate(@Param("date") Date date);
}