package cn.hospital.dao;

import cn.hospital.pojo.Section;

public interface SectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_section
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insert(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_section
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insertSelective(Section record);
}