package cn.hospital.dao;

import cn.hospital.pojo.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_user
     *
     * @mbggenerated Tue Jun 25 19:21:00 CST 2019
     */
    int updateByPrimaryKey(User record);
}